app/blueprints/main.py
from flask import redirect, render_template, abort, g, current_app as app, Blueprint, request, url_for, flash
from app.forms.url import UrlForm
from app.models.network import Network
from app.models.url import URL, Custom_URL, generate_random_string
from app.core.db import db

from app.utils.kernel import validate_url, url_exist
from app.utils.db import commit
bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index/', methods=['GET', 'POST'])
def index():
    # status = request.args.get('status')
    _ip = request.access_route[0] or request.remote_addr
    ip = Network.query.filter(Network.ip == _ip).first()
    if ip is None:
        ip = Network()
        ip.ip = _ip
        db.session.add(ip)
        commit()
        g.ip_id = ip.id

    form = UrlForm()
    if form.validate_on_submit():
        url = validate_url(form.url.data)
        if url is False:
            flash(f'URL: {form.url.data} inválida', category='danger')
            return redirect(url_for('main.index'))
        if url_exist(url.geturl()).status_code == 200:
            obj_url = URL()
            obj_url.url = url.geturl()
            if obj_url.url is False:
                flash('URL inválida', category='danger')
                return redirect(url_for('main.index'))
            obj_url.is_on = True
            obj_url.url_network_id = ip.id
            obj_url.url_short = generate_random_string(app.config['_URL_SHORT_SIZE'])
            while obj_url.url_short is False:
                obj_url.url_short = generate_random_string(app.config['_URL_SHORT_SIZE'])
            db.session.add(obj_url)
            commit()
            flash('Url cadastrada com sucesso!', category='success')
            return render_template('index.html', status=True, url=obj_url.get_short_url())
        else:
            flash(f'URL: {form.url.data} inválida, com status code {url_exist(url.geturl()).status_code}', category='danger')
            return redirect(url_for('main.index'))

    return render_template('index.html', form=form)

@bp.route('/<short>')
def short(short):
    url = URL.query.filter(URL.url_short == short).first_or_404()
    if url.check_status_url() is False:
        flash(f'URL {url.url} não está mais ativa', category='danger')
        return abort(404)
    url.hits += 1
    commit()
    return redirect(url.url)


@bp.route('/list')
@bp.route('/list/<int:page>')
def list(page=1):
    pages = URL.query.order_by(URL.created_at.desc()).paginate(page, 10, False)
    return render_template('list.html', list=pages)


@bp.app_errorhandler(404)
def handler_error_404(err):
    return render_template('errors/404.html')

@bp.app_errorhandler(500)
def handler_error_500(err):
    return render_template('errors/500.html')

app/templates/_list.html
<table class="table">
    <thead>
        <tr>
            <th scope="col">URL Nova</th>
            <th scope="col">URL Antiga</th>
            <th scope="col">Status</th>
            <th scope="col">Acessos</th>
        </tr>
    </thead>
    <tbody>
        {% for url in list.items %}
        <tr class="{{ 'table-danger' if url.status is false else '' }}">
            <td>
                {% if url.status is true %}
                <a href='{{url.get_short_url()}}' id='copy-value-{{url.url_short}}' target="_blank" class="link-secondary">{{url.get_short_url()}}</a>
                <a href="#" class="float-end table-copy" type="button" id="copy-{{url.url_short}}" data-bs-toggle="tooltip"
                title="Copiar">
                    <i class="bi bi-clipboard2 float-end"></i>
                </a>
                {% else %}
                {{url.get_short_url()}}
                {% endif %}
            </td>
            <td>
                {{url.url}}
                <img src="https://www.google.com/s2/favicons?domain={{url.url}}" class="float-end">

            </td>
            <td>{% if url.status is true %}<i class="bi bi-check-square-fill text-success"></i>{% else %}
                <i class="bi bi-x-square-fill text-danger"></i>{% endif %}
            </td>
            <td>{{url.hits}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

app/templates/index.html
{% extends 'base/base.html' %}
{% import 'macros/form.html' as macros %}

{% block content %}
<div class="row  m-2 border p-4">
  {% if form is defined %}
  <form action="" method="post">
    {{ form.csrf_token }}
    {{ macros.render_field(form.url, size=64, class='form-control', placeholder='Insira a URL', maxlength=512) }}
    <br>
    <div class="d-grid gap-2 col-4">
    {{ form.submit(class='btn btn-primary mb-3 float-left') }}
    </div>
  </form>
  {% elif status is defined %}
  <div class="input-group">
    <input class="form-control" type="text" aria-label="URL" value="{{url}}" id='short-url' disabled>
    <span class="input-group-btn">
      <button class="btn btn-outline-dark" type="button" id="copy-button" data-bs-toggle="tooltip"
        title="Copiar">
        Copiar
      </button>
    </span>
  </div>
  {% endif %}
</div>


{% endblock %}

app/templates/list.html
{% extends 'base/base.html' %}

{% block content %}

{% include '_list.html' %}
<div style="text-align: center; padding-top: 5px; font-weight: 600;">
    <p style="color:#777">
      {% if list.has_prev %}
      <a href="{{url_for('main.list',page=list.prev_num)}}">&lt;&lt; Anterior </a>
      {% else %} &lt;&lt; Anterior {% endif %} {% if list.has_next %}
      <a href="{{url_for('main.list',page=list.next_num)}}">Próxima &gt;&gt;</a>
      {% else %} Próxima &gt;&gt; {% endif %}
    </p>
  </div>
{% endblock %}